name: 'ms-reminder'
services:
  ms-reminder:
    build:
      dockerfile: ./Dockerfile.dev
    restart: always
    ports:
      - 5010:5010
    networks:
      - ms-reminder-network
    env_file:
      - .dev.env
    volumes:
      - .:/ms-reminder
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: devuser
      MONGO_INITDB_ROOT_PASSWORD: devpass
    volumes:
      - mongodbdata:/data/db
    networks:
      - ms-reminder-network

  redis:
    image: redis:7.4.1-alpine3.20
    restart: always
    command: redis-server --requirepass reminder-redis
    ports:
      - "6379:6379"
    networks:
      - ms-reminder-network
networks:
  ms-reminder-network:
    external: true

volumes:
  mongodbdata:
